#!/bin/sh
set -e

# Format Rust code
cargo fmt --all

# Format Python code
uv tool run ruff format

# Format Markdown and Workflow
npx prettier --write "**/*.{md,yml,yaml,js,ts,json}"

# Ensure all files are added after formatting
git add -A
